security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: Acme\GeekShareBundle\Entity\User, property: email }

    firewalls:

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
        main:
            pattern:      .*
            security: true
            access_denied_url: /api/user/403
            form-login:
                login_path:     /api/user/403
                use_forward:    false
                check_path:     /api/user/403
                failure_path:   null
            logout:       true
            anonymous:    true 

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }